main/urls.py
from django.urls import path
from .import views
app_name="main"
urlpatterns = [
    
    path('', views.base,name="base"),
   
    path('about/', views.about,name="about"),
    path('register/', views.register,name="register"),
    path('logout/', views.logout_request,name="logout"),
    path('login/', views.login_request,name="login"),
    path('profile/', views.profile,name="profile"),
    path('result', views.result,name="result"),

]

smartTherapist/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
 path('', include('main.urls')) ,  
 
]

main/models.py
from django.db import models
from datetime import datetime
# Create your models here.
class Admin(models.Model):
	admin_username=models.CharField(max_length=20)
	admin_password=models.CharField(max_length=100)
	email_id=models.EmailField(max_length=100)
	first_name=models.CharField(max_length=25)
	last_name=models.CharField(max_length=25)
	mobile_number=models.TextField(max_length=10)

	def __str__(self):
		return self.admin_username

class User(models.Model):
	username=models.CharField(max_length=20)
	password=models.CharField(max_length=100)
	email_id=models.EmailField(max_length=100)
	first_name=models.CharField(max_length=25)
	last_name=models.CharField(max_length=25)
	mobile_number=models.TextField(max_length=10)

	def __str__(self):
		return self.username

class User_data(models.Model):
	data=models.TextField(max_length=500)
	emotion=models.CharField(max_length=20)
	date=models.DateTimeField("date published",default=datetime.now)
	user=models.ForeignKey(User,on_delete=models.CASCADE)

	def __str__(self):
		return self.emotion

main/forms.py
from django import forms
from .models import User_data

class myForm(forms.Form):
	 data = forms.CharField()


    

main/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from main.utils import classify_dataset
from .forms import myForm
# Create your views here.
def base(request):
	return render(request=request,template_name="main/base.html",
					context={"Users": User.objects.all})


def about(request):
	return render(request=request,template_name="main/about.html")
	

def homepage(request):
	return HttpResponse("Homepage")


def register(request):
	if request.method =="POST":
		form = UserCreationForm(request.POST)
		if form.is_valid():
			stuser = form.save()
			username = form.cleaned_data.get('username')
			messages.success(request,f"New Account is succesfully created: {username}")
			login(request, stuser)
			messages.info(request,f"You are now logged in as:{username}")
			return redirect("main:base")

	form = UserCreationForm
	return render(request,"main/register.html",context={"form":form})

def profile(request):
	return render(request=request,template_name="main/profile.html")

'''def result(request,data):

	inputData=request.cleaned_data.get('data')
	result=classify_dataset(inputData)
	return render(request,"main/result.html",{"result":result} ) '''

'''def result(request):
	if request.method == 'POST':  # data sent by user
		form = myForm(request.POST)
		if form.is_valid():
			inputData=request.cleaned_data.get('formData')
			result=classify_dataset(inputData)
			form.save()  # this will save Car info to database
			return HttpResponse('data is added to database')
		else:
		  # display empty form
		form = myForm()
	return render(request, 'result.html', {'result': result})'''
def result(request):
	if request.method == 'POST': 
		form = myForm(request.POST)
		print(form)
		if form.is_valid():
			text = form.cleaned_data['data']
			text.save()
		else:
			text="wrong"
		res = classify_dataset(text)
		context = {
        'form': form,
        'text': text,
    }

		args = {'form': form , 'text': text }
	else:
		form = myForm()
	return render(request,'main/result.html',context)


	


def logout_request(request):
	logout(request)
	messages.info(request,"Succesfully logged out !")
	return redirect("main:base")

def login_request(request):
	if request.method =="POST":
		form =AuthenticationForm(request,data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username,password=password)
			if user is not None:
				login(request,user)
				messages.info(request,f"You are now logged in as:{username}")
				return redirect("main:base")
				
			else:
				messages.error(request,"Invalid username or password")
		
	form =AuthenticationForm()
	return render(request,"main/login.html",{"form" : form})

main/templates/main/about.html
{% extends "main/base.html"%}
{% load static %}
	{% block content %}

	<!-- Start About Area -->
	<section class="about-area section-gap">
		<div class="container">
			<div class="row align-items-center justify-content-between">
				<div class="col-lg-6 about-left">
					<img class="img-fluid" src="{% static 'main/img/about-img.jpg' %}" alt="">
				</div>
				<div class="col-lg-5 col-md-12 about-right">
					<div class="section-title">
						<h2>About Us</h2>
					</div>
					<div class="mb-50 wow fadeIn" data-wow-duration=".8s">
						<p>
							The purpose of this project is to overcome the problem that in a perfect world, we all have easy, affordable access to mental healthcare professionals and be able to properly treat these maladies.  

						</p>
						<p>But today we do not have that much time to go to clinic for routine checkup. So, we need something which can look after our mental health in this busy life. And also which consume less time to implement its process. 

						</p>
					</div>
						</div>
			</div>
		</div>
	</section>
	{% endblock %}
	<!-- End About Area -->

main/templates/main/base.html
<head>
	{% load static %}
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="{% static 'main/img/fav.png'%}">
	<!-- Author Meta -->
	<meta name="author" content="colorlib">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>Smart Therapist</title>
	<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,600,700,900" rel="stylesheet">
	    

   
            

	
	<link href="{% static 'main/css/linearicons.css' %}" rel=stylesheet>
	<link href="{% static 'main/css/font-awesome.min.css' %}" rel=stylesheet>
	<link href="{% static 'main/css/bootstrap.css' %}" rel=stylesheet>
	<link href="{% static 'main/css/magnific-popup.css' %}" rel=stylesheet>
	<link href="{% static 'main/css/nice-select.css' %}" rel=stylesheet>
	<link href="{% static 'main/css/animate.min.css' %}" rel=stylesheet>
	<link href="{% static 'main/css/owl.carousel.css' %}" rel=stylesheet>
	<link href="{% static 'main/css/main.css' %}" rel=stylesheet>

</head>
<body>

	


	<!-- Start Header Area -->
	<header id="header">
		<div class="container main-menu">
			<div class="row align-items-center d-flex">
				<div id="logo">
			<a href="{% url 'main:base' %}"><img src="{% static 'main/img/logo.png' %}" alt="" title="" /></a>
				</div>
				<nav id="nav-menu-container">
					<ul class="nav-menu">
						<li class=""><a class="active" href="">Home</a></li>
						<li><a  href="{% url 'main:about' %}">About</a></li>


					{% if user.is_authenticated %}
					<li><a  href="/profile">{{user.username}}'s Profile</a></li>
						<li class="menu-has-children"><a href="/{{user.username}}/records">Records</a>
							<ul>
								<li><a href="/week.html">Last week</a></li>
								<li><a href="/month.html">Last Month</a></li>
							</ul>
						</li>
						<li><a href="{% url 'main:logout' %}">Log Out</a></li>
					{% else %}	
						<li><a href="{% url 'main:register' %}">Sign Up</a></li>
					{% endif %}

					</ul>
				</nav>
			</div>
		</div>
	</header>
	<!-- End Header Area -->
	

   
<section class="home-banner-area">
		<div class="container">
			<div class="row fullscreen d-flex align-items-center">
				<div class="banner-content col-lg-6 col-md-12 justify-content-center ">


					
					<br>
		


<br>
<br>
<br>
<br>

					<h1 class="wow fadeInUp" data-wow-duration="1s" data-wow-delay="1.7s">Smart Therapist</h1>
					<div class="designation mb-50 wow fadeInUp" data-wow-duration="1s" data-wow-delay="2.1s">
						Smart way to
						
						Live Healthy
						
					</div>
					<a href="/login" class="primary-btn" data-text="Get Started">
						<span>R</span>
						<span>E</span>
						<span>A</span>
						<span>D</span>
						<span>Y</span>
										</a>
				</div>

				<div class="banner-img col-lg-6 col-md-6 align-self-end">
					<br>
					<br>
					<br>

					<img class="img-fluid" src="{% static 'D:\project\minor\smartTherapist\main\static\main\img\banner-img3.png' %}" alt="">
				</div>

			<script type="text/javascript">
		$(document).ready(function(){
    $('.messages').delay(5000).fadeOut();
});
	</script>
				

	{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
				
			</div>
		</div>
	</section>
	<!-- End banner Area -->


      	
<div class="container">
	<br>
{% block content %}
{% endblock %}
</div>

<!-- ####################### Start Scroll to Top Area ####################### -->
	<div id="back-top">
		<a title="Go to Top" href="#">
			<i class="lnr lnr-arrow-up"></i>
		</a>
	</div>
	<!-- ####################### End Scroll to Top Area ####################### -->



</body>
<script src="{% static 'main/js/vendor/jquery-2.2.4.min.js'}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	 crossorigin="anonymous"></script>
	 <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
	 <script src="{% static 'main/js/vendor/bootstrap.min.js' %}"></script>

	  <script src="{% static 'main/js/easing.min.js' %}"></script>
	  <script src="{% static 'main/js/vendor/bootstrap.min.js' %}"></script>
	  <script src="{% static 'main/js/hoverIntent.js' %}"></script>
	  <script src="{% static 'main/js/superfish.min.js' %}"></script>
	  <script src="{% static 'main/js/mn-accordion.js' %}"></script>
	  <script src="{% static 'main/js/jquery.ajaxchimp.min.js' %}"></script>
      <script src="{% static 'main/js/jquery.magnific-popup.min.js' %}"></script>
      <script src="{% static 'main/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'main/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'main/js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'main/js/jquery.circlechart.js' %}"></script>
<script src="{% static 'main/js/mail-script.js' %}"></script>

<script src="{% static 'main/js/wow.min.js' %}"></script>
<script src="{% static 'main/js/main.js' %}"></script>
 

main/templates/main/login.html
{% extends "main/base.html"%}
{% load static %}
	{% block content %}
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
<button type="submit" class="btn" >
	Login
</button>

</form>
If you dont already have an account,
<a href="/register"><strong>Register</strong></a> instead.

	{% endblock%}

main/templates/main/profile.html
{% load static %}

<head>
  <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,600,700,900" rel="stylesheet">


  
  <link href="{% static 'main/css/linearicons.css' %}" rel=stylesheet>
  <link href="{% static 'main/css/font-awesome.min.css' %}" rel=stylesheet>
  <link href="{% static 'main/css/bootstrap.css' %}" rel=stylesheet>
  <link href="{% static 'main/css/magnific-popup.css' %}" rel=stylesheet>
  <link href="{% static 'main/css/nice-select.css' %}" rel=stylesheet>
  <link href="{% static 'main/css/animate.min.css' %}" rel=stylesheet>
  <link href="{% static 'main/css/owl.carousel.css' %}" rel=stylesheet>
  <link href="{% static 'main/css/main.css' %}" rel=stylesheet>
</head>
<body>
<section class="about-area section-gap">
    <div class="container">
      <div class="row align-items-center justify-content-between">
        <div class="col-lg-6 about-left">
          <img class="img-fluid" src="{% static 'main/img/about-img.jpg' %}" alt="">
        </div>
        <div class="col-lg-5 col-md-12 about-right">
          <div class="section-title">
            <h3>How was your day???</h3>
          </div>
          <div class="mb-50 wow fadeIn" data-wow-duration=".8s">
           <form action="{% url 'main:result' %}" id="usrform" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {{ form.path }}
<textarea rows="4" cols="50" name="formData" form="usrform">
</textarea><br/>
    <input type="submit" value="Submit">

<input type="reset" value="Clear">

   </form> 
           
        
<a class="active" href="{% url 'main:base' %}" >Home</a></li>

            
          </div>
                  </div>
      </div>
    </div>
  </section>
<script src="{% static 'main/js/vendor/jquery-2.2.4.min.js'}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
   crossorigin="anonymous"></script>
   <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
   <script src="{% static 'main/js/vendor/bootstrap.min.js' %}"></script>

    <script src="{% static 'main/js/easing.min.js' %}"></script>
    <script src="{% static 'main/js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'main/js/hoverIntent.js' %}"></script>
    <script src="{% static 'main/js/superfish.min.js' %}"></script>
    <script src="{% static 'main/js/mn-accordion.js' %}"></script>
    <script src="{% static 'main/js/jquery.ajaxchimp.min.js' %}"></script>
      <script src="{% static 'main/js/jquery.magnific-popup.min.js' %}"></script>
      <script src="{% static 'main/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'main/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'main/js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'main/js/jquery.circlechart.js' %}"></script>
<script src="{% static 'main/js/mail-script.js' %}"></script>

<script src="{% static 'main/js/wow.min.js' %}"></script>
<script src="{% static 'main/js/main.js' %}"></script>
</body>

main/templates/main/register.html
{% extends "main/base.html"%}
{% load static %}
	{% block content %}
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
<button type="submit" class="btn" >
	Register
</button>

</form>
If you already have an account,
<a href="/login"><strong>Login</strong></a> instead.

	{% endblock%}

main/templates/main/result.html
{% load static %}

<head>
  <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,600,700,900" rel="stylesheet">


  
  <link href="{% static 'main/css/linearicons.css' %}" rel=stylesheet>
  <link href="{% static 'main/css/font-awesome.min.css' %}" rel=stylesheet>
  <link href="{% static 'main/css/bootstrap.css' %}" rel=stylesheet>
  <link href="{% static 'main/css/magnific-popup.css' %}" rel=stylesheet>
  <link href="{% static 'main/css/nice-select.css' %}" rel=stylesheet>
  <link href="{% static 'main/css/animate.min.css' %}" rel=stylesheet>
  <link href="{% static 'main/css/owl.carousel.css' %}" rel=stylesheet>
  <link href="{% static 'main/css/main.css' %}" rel=stylesheet>
</head>
<body>
<section class="about-area section-gap">
    <div class="container">
      <div class="row align-items-center justify-content-between">
        <div class="col-lg-6 about-left">
          <img class="img-fluid" src="{% static 'main/img/about-img.jpg' %}" alt="">
        </div>
        <div class="col-lg-5 col-md-12 about-right">
          <div class="section-title">
            <h3>You are feeling {{text}} </h3>
          </div>
           <div class="mb-50 wow fadeIn" data-wow-duration=".8s">
           <a class="active" href="{% url 'main:base' %}" >Home</a></li>  
           </div>
                  </div>
      </div>
    </div>
  </section>
<script src="{% static 'main/js/vendor/jquery-2.2.4.min.js'}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
   crossorigin="anonymous"></script>
   <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
   <script src="{% static 'main/js/vendor/bootstrap.min.js' %}"></script>

    <script src="{% static 'main/js/easing.min.js' %}"></script>
    <script src="{% static 'main/js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'main/js/hoverIntent.js' %}"></script>
    <script src="{% static 'main/js/superfish.min.js' %}"></script>
    <script src="{% static 'main/js/mn-accordion.js' %}"></script>
    <script src="{% static 'main/js/jquery.ajaxchimp.min.js' %}"></script>
      <script src="{% static 'main/js/jquery.magnific-popup.min.js' %}"></script>
      <script src="{% static 'main/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'main/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'main/js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'main/js/jquery.circlechart.js' %}"></script>
<script src="{% static 'main/js/mail-script.js' %}"></script>

<script src="{% static 'main/js/wow.min.js' %}"></script>
<script src="{% static 'main/js/main.js' %}"></script>
</body>